### ISSUE TITLE
Add "libretro" Runner Defaults

### ISSUE THREAD

**Issue by RobLoach** [lutris/website#189]
Add some of the libretro core installers when adding a game, when it matches a given platform....

## Dreamcast - reicast
```
files:
- rom: N/A:Select the GDI, or ISO file
game:
  core: reicast
  main_file: rom
```

## Playstation - Beetle PSX
```
files:
- rom: N/A:Select the ISO file
game:
  core: beetle_psx
  main_file: rom
```

One example installer that uses this pattern is: https://lutris.net/games/marvel-vs-capcom-clash-of-super-heroes/

Was looking around for where this is added, and couldn't find them. Any tips?
