### ISSUE TITLE
Battle.Net Installer Specifies a Glorious Eggroll Wine build

### ISSUE THREAD

**Issue by gardotd426** [lutris/website#631]
I already have GE's Lutris builds installed and so I don't know if Lutris even provides download links for them, but the Blizzard Battle.Net install script specifies `lutris-GE-Proton7-16-x86_64` as the wine version:

```
wine:
  dxvk: true
  esync: true
  overrides:
    windows.networking: disabled
    version: lutris-GE-Proton7-16-x86_64https://www.reddit.com/r/linux_gaming/comments/vof0r2/unable_to_install_battlenet_via_lutris/
```

[Install Script](https://lutris.net/games/install/8519/view)

[This is causing problems for people who don't have that version of Wine installed into `~/.local/share/lutris/runners/wine`](https://www.reddit.com/r/linux_gaming/comments/vof0r2/unable_to_install_battlenet_via_lutris/):
![Screenshot_20220701_073848](https://user-images.githubusercontent.com/54234607/176887765-5a4323b4-3a97-4505-8689-2f96866b786b.png)

I know that at least in the past, if a wine version was specified, it was required to be a build that Lutris actually distributed, and if the user hadn't installed it from the Lutris wine version manager, then it would install itself. So unless that's changed, then it seems like the person that wrote this installer is for some reason specifying a Wine build that Lutris doesn't distribute, which is pretty stupid. If Lutris does distribute GE builds all the sudden, then something is broken because Lutris isn't downloading and installing the builds when they are specified. 

The website used to allow users to report problems with installers or fork install scripts, which was what I was going to do, I was just going to remove the Wine GE specification, but both of those options are not available on the Battle.NET installer, so this was the only available option.
