### ISSUE TITLE
YAML missing doublequoted numbers causing install script to fail when passed to functions using PyGobject

### ISSUE THREAD

**Issue by jmczab** [lutris/website#724]
If this is the wrong place, please let  me know.
This is not an issue with a specific game, but the installer view output from the site.

On the [Civilization IV GoG installer](https://lutris.net/games/install/11366/view) as an example, view the installer and the input_menu, line 41-50.

When the YAML is viewed, copied and used as an installer, the script is missing quotes around the input_menu values. This results in them being assigned a type of int, and PyGobject, expecting a string, throws an installer error as a result.

The options under input_menu should be enclosed in quotes - double or single quotes, whatever your preference :)

Here is what comes out of the website 41-50 when you view the YAML:-
```
   - input_menu:
       description: 'Please choose game''s language:'
       id: LANG
       options:
       - 0: English
       - 1: French
       - 2: German
       - 3: Italian
       - 4: Spanish
       preselect: 0
```

Here is what would 41-50 should look like  (changes 45-49,) and will work correctly when parsed by the Lutris installer. 
```
   - input_menu:
       description: 'Please choose game''s language:'
       id: LANG
       options:
       - '0': English'
       - '1': 'French'
       - '2': 'German'
       - '3': 'Italian'
       - '4': 'Spanish'
       preselect: 0
```

Note that the download/JSON installer gets correctly parsed, as the values are quoted: -
```
 88             "input_menu": {
 89               "description": "Please choose game's language:",
 90               "id": "LANG",
 91               "options": [
 92                 {
 93                   "0": "English"
 94                 },
 95                 {
 96                   "1": "French"
 97                 },
 98                 {
 99                   "2": "German"
100                 },
101                 {
102                   "3": "Italian"
103                 },
104                 {
105                   "4": "Spanish"
106                 }
107               ],
108               "preselect": 0
109             }
```
